### PR TITLE
SFTP script cleanup and Transactional Gift file recognition

### PR DESCRIPTION
**Pull request by atironati**
When we're done the SFTP script gon' be like
osprey vertibird

### CODE REVIEW

**Comment by EdHurtig** [comment]
LOL!

**Comment by atironati** [comment]
yea there are a whole bunch of changes we made but I have to make a bunch of individual commits for all of them so they make sense, but I didn't feel like doing them all right now

**Comment by jeffbyrnes** [comment]
@atironati I encourage you to review [A Note About Git Commit Messages](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html), and, if you please, amend some of these to adhere to that standard a bit strongly.

**Comment by atironati** [comment]
@jeffbyrnes yesterday Eric and I finished up the infrastructure changes for the SFTP script as represented here. Mad props to @eherot for his help with this work. I am working on the modifications that spurred this work now, but feel free to take a look and make comments on the current changes if you see fit

**Comment by jeffbyrnes** [comment]
@atironati I’ll take a look through. Nicely done all-around though!

**Comment by jeffbyrnes** [comment]
@atironati @eherot this looks awesome. Thanks for leveling up this cookbook so much!

**Comment by jeffbyrnes** [comment]
@atironati by the way, I’d probably just merge this in now, then continue your modifications on a new branch; this one’s pretty huge already.

**Pull request merged**
